### PR TITLE
Magento 1.9.4.4

### PR DESCRIPTION
**Pull request by JeroenBoersma**
This is the Magento 1.9.4.4 upgrade

Splitted Copyright/packageXML/code changes in 3 commits

To compare and validate:
* Go to https://magento.com/tech-resources/download
* Download 1.9.4.4. tarball
* extract
* remove all files in this repo
* copy all files with permissions into repo `cp -rvp magento/. .`
* `git add var/packages` easy / commit
* `git status -s | while read s f; do git diff $f | grep '^+ ' | grep -v copyright || git add $f; done` add copyright only / commit
* `git add -p .` groom last copyright updates / amend in last commit
* `git add .` commit code changes

### CODE REVIEW

**Comment by BassemN** [comment]
@JeroenBoersma Many thanks for splitting this update into 3 commits

**Comment by EricSeastrand** [comment]
`diff` confirms that these changes match the official version downloaded from https://magento.com/tech-resources/download
Good to merge.

**Comment by davidwindell** [comment]
LGTM

**Review by Flyingmana — APPROVED** [review]

**Comment by davidwindell** [comment]
@Flyingmana please can you update Packagist? We can't install with composer at the moment:

```
    - The requested package openmage/magento-mirror 1.9.4.4 exists as openmage/magento-mirror[1.9.4.3] but these are rejected by your constraint.
```

**Comment by davidwindell** [comment]
Ignore that, looks like the composer.json has been deleted. I'll raise a PR to restore it

**Comment by Flyingmana** [comment]
the openmage/magento-mirror was at no point added to packagist

**Comment by davidwindell** [comment]
@Flyingmana that's fine, it's the fact that the composer.json was deleted unintentionally in this release. I've brought it back in #83

**Comment by BassemN** [comment]
Magento 1.9.4.5 has been released https://magento.com/tech-resources/download#download2358

**Pull request merged**
