### PR TITLE
Updated to pristine copy of 1.9.4.5 from magento.com

### PR DESCRIPTION
**Pull request by EricSeastrand**
Community: Please help us by verifying that my branch matches the official release, and comment accordingly.
Thanks!

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
I've verified...

* GOTO Magento.com downloads
* download 1.9.4.5 zip (tar.gz didn't work for me today)
* delete all files
* extract zip
* copy all files into repo
* add and commit

Added `wilcodeforfood` remote and compared the result.

LOOKS GOOD TO ME!
Also pushed to my remote if you're curious.

**Comment by BassemN** [comment]
@Flyingmana please merge

**Comment by Flyingmana** [comment]
@BassemN did you Review this PR?
We need 2 approving Reviewers

**Comment by BassemN** [comment]
@Flyingmana Yes, I reviewed this PR and it is the same results, verified.

```
wget https://github.com/willcodeforfood/magento-mirror/archive/1.9.4.5.zip ;
unzip 1.9.4.5.zip ;
diff -r magento/ magento-mirror-1.9.4.5/ ;
```

**Pull request merged**
