### PR TITLE
Updating to pristine 1.9.3.10 version

### PR DESCRIPTION
**Pull request by EricSeastrand**
I don't think I created the tag correctly. Happy to fix that if you let me know what the process is.

Here's what I've done
1. Download pristine 1.9.3.10 from https://magento.com/tech-resources/download
2. Forked the OpenMage repo (actually I already had a fork, so I did `git fetch upstream` instead)
3. `rm -rf`ed all files in the root
4. Did a `git status | grep deleted` to find and delete files that were removed between `1.9.3.9` and `1.9.3.10`.  
5. `git add . && git commit -m "Updating to pristine 1.9.3.10 version" && git push`

Testing procedure:
1. Download the zipped version of my commit from GitHub
2. Extract pristine files downloaded from Magento into a separate dir
3. `diff -r ~/Downloads/magento-mirror-magento-1.9 ~/Downloads/magento-1.9.3.10-pristine/`
4. Observed that `diff` found no changes.
5. `echo "testing that diff works" >> RELEASE_NOTES.txt`
6. Run diff command again, observe that it finds this deliberate change (just to confirm that diff isn't broken)

How I created the tag (probably wrong; please advise):
1. `git tag 1.9.3.10`
2. `git push origin 1.9.3.10`
3. Created this pull request.

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
Verified locally with same result!

**Comment by spinsch** [comment]
Same here.

```bash
wget https://github.com/willcodeforfood/magento-mirror/archive/1.9.3.10.zip ; unzip 1.9.3.10.zip ; diff -r ~/Downloads/magento/ magento-mirror-1.9.3.10/ ; rm -rf 1.9.3.10.zip magento-mirror-1.9.3.10/
```

**Comment by bassplayer7** [comment]
@LeeSaferite @drobinson and @Flyingmana, anyone available to review this PR?

**Comment by Flyingmana** [comment]
did not have time for a review yet, but I can say, we will take care of creating the Tag after merging (Iam not sure you can even add Tags via PR)

Anyway, thank you 3 a lot for providing and reviewing already :)

**Review by Flyingmana — APPROVED** [review]
compared with the magento provided release(identical), and also checked trough all the files and everything seems to be ok

**Comment by Flyingmana** [comment]
@LeeSaferite @drobinson 
sadly I cant merge here, so one of you needs to do it

**Comment by LeeSaferite** [comment]
I verified the PR contents were identical to the contents of the distribution file as well.

6e3dc40b7201d2bffb3d21c8b10c99d96efe48211908cafa8f6b5d69b6bdb84d  magento-1.9.3.10-2018-09-18-03-21-10.tar.bz2

**Pull request merged**
