### PR TITLE
Import Magento Release 1.9.2.1

### PR DESCRIPTION
**Pull request by ToonSpin**

### CODE REVIEW

**Comment by davidwindell** [comment]
:+1: :+1: :+1:

**Comment by davidwindell** [comment]
:+1: Ping @LeeSaferite

**Comment by LeeSaferite** [comment]
I'll get to this after work today.

**Comment by LeeSaferite** [comment]
Ok, I've had time to check this now so I'll merge. Thanks!

**Comment by ToonSpin** [comment]
No problem @LeeSaferite, thanks for merging. Your repo has helped me out in the past, glad to be able to contribute.

**Comment by ktomk** [comment]
@ToonSpin: Can you provide reference of the filename of the package you created this PR from including checksums of the file?

**Comment by LeeSaferite** [comment]
I can provide them in the morning. 

I personally grabbed the release file from Magento and did the import again just to do a compare as I don't know @ToonSpin at all. According to git the two were identical.

In the future I'll start adding the filename and fingerprint of the file used to do the import. 

If anyone has any suggestions for more information that should be included, feel free to comment.

**Comment by ToonSpin** [comment]
I can certainly see where @ktomk is coming from, and if I were @LeeSaferite (who indeed does not know me at all) I would have done the exact same thing. Let me provide a short walkthrough of how I created the commit:

On my Ubuntu box I [downloaded](https://www.magentocommerce.com/download) Magento 1.9.2.1, file name was `magento-1.9.2.1.tar.gz`. Running `cksum magento-1.9.2.1.tar.gz` on my system yields:

```
272010853 24437578 magento-1.9.2.1.tar.gz
```

The next steps:
1. unpack the tar.gz to a directory
2. clone this repository and copy/move its `.git` directory to the unpacked tar.gz directory
3. set Git to ignore file modes
4. add everything except the `.gitignore` and commit

You should get an identical commit to mine if you follow the above steps, but note that the commit hash will be different, because among other things, you have a different name and e-mail address.

**Comment by ToonSpin** [comment]
@ktomk there is a way to verify that the above yields the exact same files as what I did. Run

```
git show COMMIT --no-patch --format=format:%T
```

Where COMMIT is the commit you want to inspect. Try this on two different commits, and if the hashes match, then all of the files in the entire commits are exactly the same.

**Comment by tkn98** [comment]
@ToonSpin: Thanks for all the clarifications you've made and I'm sorry I wasn't equally differentiated when asking for feedback:

I was concerned about the filename (when I download from that Magento vendor website I get filenames like `magento-1.9.2.1.tar-2015-08-03-06-35-45.gz`) and then the checksum of that package.

This is what I get from a current download:

The currently given file behind Cookie-Login is:
- File: `magento-1.9.2.1.tar-2015-08-03-06-35-45.gz`
- MD5: `61faafc54f3f1e81bd2d89f358aaba80`
- SHA1: `41b4b9ae2e02fa9fecf3330e19790120aeeced92`

How did I do it? Here is a short line-up of commands and their parameters used. Download was by hand from the vendors website.

```
$ ls -go --full-time magento-1.9.2.1.tar-2015-08-03-06-35-45.gz
-rw-r----- 1 24437578 2015-08-06 09:29:01.422523367 +0200 magento-1.9.2.1.tar-2015-08-03-06-35-45.gz

$ md5sum magento-1.9.2.1.tar-2015-08-03-06-35-45.gz
61faafc54f3f1e81bd2d89f358aaba80  magento-1.9.2.1.tar-2015-08-03-06-35-45.gz

$ shasum magento-1.9.2.1.tar-2015-08-03-06-35-45.gz
41b4b9ae2e02fa9fecf3330e19790120aeeced92  magento-1.9.2.1.tar-2015-08-03-06-35-45.gz
```

For the previous release we started to track these in the magerun repo as it has a magento installer feature, see for references here: https://github.com/netz98/n98-magerun/issues/609

Despite Magento is marketed with version numbers (like 1.9.2.0), it indeed does timestamp versioned releases. It think it is a good idea to make visible which release has been mirrored by having that meta-data (the timestamp and checksums of the package) with the commit. I already asked for 1.9.2.0 [here](https://github.com/netz98/n98-magerun/issues/609#issuecomment-124213201).

For the files itself (not the package), it's possible to reverse engineer for which the git commands you presented are useful. But it's a bit burdensome for documentation purposes to find out afterwards.

**Pull request merged**
