### PR TITLE
Module 3

### PR DESCRIPTION
**Pull request by RomanKrut**

### CODE REVIEW

**Comment by LeeSaferite** [comment]
@krutkoroma79911  Could you please stop making PRs against this repo for your personal modules?

**Comment by RomanKrut** [comment]
I`m so sorry, i`m new on github and i trying to create pull request to
forked branch, can you help me?

2018-01-10 16:40 GMT+02:00 Lee Saferite <notifications@github.com>:

**Comment by LeeSaferite** [comment]
On the left side it says 'base fork' with a drop down. Make sure this dropdown shows your repo, not the OpenMage repo.

**Comment by RomanKrut** [comment]
Ohh, thanks, man, and sorry again.  You will never see pull requests from
me! Good luck


2018-01-10 16:44 GMT+02:00 Lee Saferite <notifications@github.com>:

**Comment by LeeSaferite** [comment]
We have another repo that does accept PRs (https://github.com/OpenMage/magento-lts) for bug fixes and such. This one is meant to be just a mirror of the Magento code.

**Pull request closed without merging**
