### PR TITLE
Import Magento Release 1.9.2.3

### PR DESCRIPTION
**Pull request by JosephMaxwell**
@LeeSaferite: here is the latest Magento code with the new `.3` code.

### CODE REVIEW

**Comment by davidwindell** [comment]
Ping @LeeSaferite

**Comment by BassemN** [comment]
@LeeSaferite Please add the new release 1.9.2.3

**Comment by LeeSaferite** [comment]
@JosephMaxwell I used your PR, but had to fix it.

My process for importing a new release is:

```
cd {magento repo root}
rm -rf * .ht*
tar xvf --strip-components=1 {new release tarball}
git add -A .
git commit -m "Import Magento Release {version number}"
git tag {version number}
git push origin {branch} {version number}
```

This basically removes EVERY file except .gitignore and then uses the new versions. The reason I point this out is your PR was missing the changes to the /var/package directory.

**Comment by JosephMaxwell** [comment]
@LeeSaferite: I appreciate the tip! Thank you for the script.

**Comment by LeeSaferite** [comment]
The file used for verifying this PR

```
openssl sha1 magento-1.9.2.3-2016-01-20-03-04-11.tar.bz2
```

The resulting fingerprint

```
636a20ab4ace92c2a0617612f1bad867a2bd344f
```

**Pull request merged**
