### PR TITLE
Import Magento Release 1.9.3.7

### PR DESCRIPTION
**Pull request by Schrank**

### CODE REVIEW

**Comment by drobinson** [comment]
Thanks @Schrank !

**Comment by Schrank** [comment]
I wonder why .gitignore is missing. Did you add it by hand?

**Comment by drobinson** [comment]
I was wondering the same thing so I checked the core sources manually for 1.9.3.7 and 1.9.3.6 and it's not present in either.  I think it makes sense to keep this as a true mirror of the released codebase so I'm OK with it being removed.  @LeeSaferite do you have thoughts on that?  You added it in the 1.6 release import

**Comment by drobinson** [comment]
Actually, looks like that was just the last edit.  In this day and age I would hope not having a default .gitignore would not cause issues with people's setups for this repo.

**Comment by LeeSaferite** [comment]
I'm ok either way honestly.

**Comment by BassemN** [comment]
Version 1.9.3.8 has been released.

**Pull request merged**
