### PR TITLE
Upgraded to Magento 1.9.3.8

### PR DESCRIPTION
**Pull request by JeroenBoersma**
* Applied diff 1.9.3.7 -> 1.9.3.8
  CE-1.9.3.7-1.9.3.8-2018-02-23-05-55-20.diff

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
Have a lovely day all

**Comment by EricSeastrand** [comment]
I have verified that this branch is identical to a pristine copy of 1.9.3.8 downloaded from the official Magento site using the following method:

[ First I downloaded Magento and extracted it to ./pristine-1.9.3.8 ]
```
git clone git@github.com:JeroenBoersma/magento-mirror.git
cd magento-mirror
git checkout magento-1.9.3.8
cd ..
diff -r magento-mirror pristine-1.9.3.8/ --exclude=.git
```
Output is empty, indicating there are no differences.

**Comment by BassemN** [comment]
@drobinson @LeeSaferite  Please merge and tag

**Comment by drobinson** [comment]
Thanks all! Tag here: https://github.com/OpenMage/magento-mirror/releases/tag/1.9.3.8

**Comment by BassemN** [comment]
@LeeSaferite  @drobinson Off topic suggestion but I don't know where to discuss this. Can you create a repository for Magento2 production version? As we know that Magento2 has an official repository but it doesn't intend to be used in the production but it is used for contribution as the structure is different also they have composer but it just updates the dependencies not the main magento2 app.
It will be great if you added a mirror to http://www.magentocommerce.com/download

**Pull request merged**
