### PR TITLE
[FIX] return annotation of getScript in helper core/js

### PR DESCRIPTION
**Pull request by sebastianwagner**

### CODE REVIEW

**Comment by avra911** [comment]
sorry, but this change was in an official magento update or patch? i thought this repo is meant to be an exact copy of the Magento

cc @LeeSaferite 

Best regards,
R

**Comment by sebastianwagner** [comment]
Indeed! See OpenMage/magento-lts#8.

**Comment by avra911** [comment]
OpenMage/magento-lts it is a fork that accepts fixes, but OpenMage/magento-mirror should be an exact copy of magento, with bugs :)

**Comment by avra911** [comment]
do i miss something? i think is the other way arround :)

**Comment by LeeSaferite** [comment]
You are 100% correct. The pull request was merged in error and has been reverted.

**Comment by LeeSaferite** [comment]
If there were a way for me to disable pull requests on this repo I would.

**Comment by avra911** [comment]
thanks you both

best regards,
R

**Comment by Flyingmana** [comment]
you still could do a force push, to revoke the merge completely from history

**Pull request merged**
