### PR TITLE
Import Magento Release 1.9.3.2

### PR DESCRIPTION
**Pull request by tjons**
This is the latest version: 1.9.3.2

### CODE REVIEW

**Comment by drobinson** [comment]
Looks like you missed .htaccess and .htaccess.sample - would you mind adding those?

**Comment by tjons** [comment]
@drobinson I added them. Sorry about that. Please let me know if I'm missing anything else.

**Comment by JosephMaxwell** [comment]
@drobinson: at the risk of being a nag here, would you be able to merge this? We use this repo for our CI, and are needing to update our clients.

**Comment by LeeSaferite** [comment]
I created another PR with the code and copyright changes split into two commits so it's clear what actually changed. See #45

**Comment by drobinson** [comment]
Ah sorry, I didn't see the feedback here....must be some issues with my Github notifications...nonetheless #45 is merged now.

**Comment by JosephMaxwell** [comment]
@drobinson and @LeeSaferite: thank you.

**Comment by tjons** [comment]
@LeeSaferite and @drobinson thanks for doing this.

**Pull request closed without merging**
