### PR TITLE
Updated to Magento 1.9.4.3

### PR DESCRIPTION
**Pull request by SnowCommerceBrand**
Downloaded and added the ver 1.9.4.3  - Added Oct 8, 2019 from https://magento.com/tech-resources/download.

### CODE REVIEW

**Comment by EricSeastrand** [comment]
I have confirmed using `diff` that the contents of SnowCommerceBrand's repo are identical to the one downloaded from Magento's official site. Well, except for the `composer.json` that was recently pulled into this repo.

**Review by Flyingmana — APPROVED** [review]
did also compare it, and it matches (besides the composer.json)

**Comment by davidwindell** [comment]
@drobinson can you action the review for us?

**Review by colinmollenhour — APPROVED** [review]
I didn't do a compare, but I skimmed the significant code changes if it makes any difference. :)

**Comment by BassemN** [comment]
Please create a tagged release 1.9.4.3

**Comment by Flyingmana** [comment]
just did, thank you for reminding :)

**Pull request merged**
