### PR TITLE
Update to Magento Community Edition 1.9.1

### PR DESCRIPTION
**Pull request by avra911**

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Thank you for the PR, but I checked this PR against the vanilla sources and I think you made a mistake in your commit. There are files in your branch that are not in the 1.9.1.0 tarball.

I've imported the latest tarball from Magento an pushed it here.  

As a reference, when I deploy a new tarball from Magento, this is what I run:
cd {repo root}
rm -rf \* .htaccess*
ls -la
[verify all dirs/files except .git and .gitignore are gone]
tar xvf {tarball} --strip-components=1
git add -A .
git commit -m "Import Magento Release {version}"
git tag {version}
git push origin magento-{major/minor} {version}

The full removal of the source code and the '-A' when adding ensures that all file removals are captured as part of the commit.

**Comment by avra911** [comment]
strange, i think you mean the other way arround, because you have now 11,326 changed files againts 10.509, which means probably i missed some files due to the fact that i am using filemode set to false

thanks,
R

**Comment by LeeSaferite** [comment]
Deleted files count as changed files.
I just ran a file count on your version and mine.
mine: 12854
yours: 13671

**Comment by avra911** [comment]
ah, i see, you are right, i think i know what happend

thanks for updating the repo, i changed my fork to correspond to yours now

Best regards,
R

**Pull request closed without merging**
