### PR TITLE
Better HTML tagging

### PR DESCRIPTION
**Pull request by blopa**
Just a small tweak to make the HTML tagging better by removing an unnecessary <li> tag

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Why did you move the code like this?  Are the two possible situations mutually exclusive?

**Comment by blopa** [comment]
I find this way better than the regular HTML tagging from the original source. It removes the uneeded use of the li tag twice. It's just a organized version of the same code.

**Comment by erfanimani** [comment]
This is just a Magento mirror of the official code and should be an exact copy right? @blopa

**Comment by thaiphan** [comment]
You're mixing tabs and spaces.

**Comment by davidwindell** [comment]
This should be raised against https://github.com/OpenMage/magento-lts, not here. Can you close?

**Pull request closed without merging**
