### PR TITLE
Restore composer.json

### PR DESCRIPTION
**Pull request by davidwindell**
This was deleted in #82 I think by mistake. Can you also update the tag?

### CODE REVIEW

**Comment by Flyingmana** [comment]
Good catch, that was not intended.
But actually there was a plan to remove it again, as some people complained of the mirror not beeing completely identical to the releases because of this. (Which is why it was not added to packagist)
And its still possible to reference this repository over your project composer.json I think, although I do not have an exact example, I think @LeeSaferite had one

**Comment by JeroenBoersma** [comment]
Ah, I never knew it was added to packagist.org in the first place :)
I just go and do the dumb stuff, that is synchronizing with Magento.com donwloads.

Will keep in mind if a next time will come...

**Comment by davidwindell** [comment]
@Flyingmana I guess you're referring to something like http://burgiblog.com/2012/03/08/depending-on-packages-without-composer-json-in-composer-php-dependency-manager/

I think we'll probably just fork the repo and list our fork on packagist, will be much less maintenance!

**Comment by Schrank** [comment]
Working example:
```
{
    "name": "firegento/magento-shop",
    "authors": [
        {
            "name": "Fabian Blechschmidt",
            "email": "fabian@winkelwagen.de",
            "homepage": "https://www.firegento.com"
        }
    ],
    "license": "proprietary",
    "type": "magento-source",
    "minimum-stability": "dev",
    "require": {
        "magento-hackathon/magento-composer-installer": "^4.0",
        "aydin-hassan/magento-core-composer-installer": "^2.0",
        "firegento/magento": "1.9.4.5",
        "aoepeople/aoe_scheduler": "^1.5",
        "firegento/magesetup": "^2.4",
        "firegento/pdf": "^1.4",
        "colinmollenhour/cm_orderproducts": "dev-master",
        "diglin/diglin_github": "dev-master",
        "fooman/emailattachments": "dev-master",
        "payone-gmbh/magento-1": "dev-master",
        "magento-hackathon/hackathon-site-theme": "dev-master",
        "elgentos/sendinvoiceemail": "dev-master",
        "firegento/mageuc-supporter": "dev-master",
        "buro71a/form-submission-spam-protect": "dev-master"
    },
    "require-dev": {
        "roave/security-advisories": "dev-master"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.firegento.com",
            "exclude": ["firegento/magento"]
        },
        {
            "type": "vcs",
            "url": "https://github.com/magento-hackathon/hackathon-site-theme"
        },
        {
            "type": "vcs",
            "url": "https://github.com/elgentos/SendInvoiceEmail"
        },
        {
            "type": "vcs",
            "url": "git@bitbucket.org:buro71a/b71a_formsubmissionspamprotect.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/firegento/m1-mageuc-supporter"
        },
        {
            "type": "package",
            "package": {
                "name": "firegento/magento",
                "version": "1.9.4.5",
                "source": {
                    "url": "https://github.com/OpenMage/magento-mirror.git",
                    "type": "git",
                    "reference": "origin/1.9.4.5"
                }
            }
        }
    ],
    "extra": {
        "magento-root-dir": "htdocs",
        "magento-deploystrategy": "copy",
        "auto-append-gitignore": false,
        "magento-force": true,
        "magento-core-deploy": {
            "excludes": [
                "app/etc/local.xml",
                "dev",
                "downloader"
            ],
            "git-ignore-append": false
        }
    }
}

```

Currently updating firegento shop, so bear with me about the naming.

**Comment by Schrank** [comment]
Working example for composer.json:
```
{
    "name": "firegento/magento-shop",
    "type": "magento-source",
    "minimum-stability": "dev",
    "require": {
        "magento-hackathon/magento-composer-installer": "^4.0",
        "aydin-hassan/magento-core-composer-installer": "^2.0",
        "firegento/magento": "1.9.4.5",
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.firegento.com",
            "exclude": [
                "firegento/magento"
            ]
        },
        {
            "type": "package",
            "package": {
                "name": "firegento/magento",
                "version": "1.9.4.5",
                "type": "magento-core",
                "source": {
                    "url": "https://github.com/mage-one-com/magento-1",
                    "type": "git",
                    "reference": "5bf57f3c797c4eecf1f647a940e9aa1d1fec61d7"
                }
            }
        }
    ],
    "extra": {
        "magento-root-dir": "htdocs",
        "magento-deploystrategy": "copy",
        "auto-append-gitignore": false,
        "magento-force": true,
        "magento-core-deploy": {
            "excludes": [
                "app/etc/local.xml",
                "dev",
                "downloader"
            ],
            "git-ignore-append": true
        }
    }
}
```

You can use the open mage repository as well

**Pull request closed without merging**
