### PR TITLE
add composer.json

### PR DESCRIPTION
**Pull request by ioweb-gr**
I've found your repo since firegento decided to archive theirs in favour of your repos. Would you mind adding a composer.json file here in this mirror repo for us who are not yet ready to migrate to LTS?  It would help us be able to still use composer for updating our current installations until June 2020 while preparing to migrate to LTS. 

Our other choice would be to maintain our own fork of this repo but I think it would be better to add it here and declare on packagist.

### CODE REVIEW

**Review by Flyingmana — APPROVED** [review]

**Comment by ioweb-gr** [comment]
Any ideas when this can be merged if everyone agrees?

**Comment by EricSeastrand** [comment]
Historically, the maintainers of this repo have declined to merge anything other than the pristine version of Magento obtained from the official site.
Maintaining your own fork isn't ideal but it works well for my company and allows us to roll out updates more quickly (this repo can be slow to approve PRs for new releases). I describe [the workflow for it here](https://github.com/OpenMage/magento-mirror/pull/75#issuecomment-508825556).

**Comment by mark-netalico** [comment]
I don't think it really hurts to have a composer.json file. I can't think of any downsides.

**Comment by ioweb-gr** [comment]
I see @willcodeforfood . I didn't know this has already been asked. However in the past we had a good alternative from firegento's fork. Now there's nothing. I guess if the repo owners are so against it we'll have to maintain our own fork as well as you did. It was our initial thought as well before I decided to open the pull request.

**Comment by mark-netalico** [comment]
@Flyingmana approved it so I don't think there's strong opposition.

**Comment by Flyingmana** [comment]
and I currently only wait for other supporters. ( We try to always have at least 2 approving Reviewers, with a goal of 3)
But, if we do not get additional reviews, but also no strong argument against it, I will merge it by end of the week.

**Review by kkrieger85 — APPROVED** [review]

**Comment by ioweb-gr** [comment]
Thank you very much :) Really appreciated

**Comment by ioweb-gr** [comment]
It would be also awesome if you could add the repo to packagist for easier deployment :)

**Comment by Flyingmana** [comment]
thats something only @drobinson or @LeeSaferite can do currently.

if thats not happening during the next week, I will look for a plan B

**Comment by Flyingmana** [comment]
after talking with @LeeSaferite I see I have to revert adding the composer.json, as the repository is meant as exact copy.
Instead we will provide an example, how the repository can be used without the need of it having a composer.json

**Pull request merged**
