### PR TITLE
Updated to Magento 1.9.3.9

### PR DESCRIPTION
**Pull request by JeroenBoersma**
- which goes with SUPEE-10752

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
Please also include the tag 1.9.3.9!

Howto reproduce:
- Goto https://magento.com/tech-resources/download#download2221
- Download archive
- remove all files from local copy
- untar and remove docroot "magento"
- add and push

**Comment by EricSeastrand** [comment]
I have done a `diff -r` to verify that [commit `a55ff8cfcffc5ec9fd60ae0fe090cb4ebd334d81`](https://github.com/OpenMage/magento-mirror/tree/a55ff8cfcffc5ec9fd60ae0fe090cb4ebd334d81) is identical to [the file downloaded from the official Magento site](https://magento.com/tech-resources/download#download2221).

Both versions are identical. Thanks @JeroenBoersma !

**Comment by BassemN** [comment]
Off topic question, If I updated my website to 1.9.3.9 from 1.9.3.7 should I apply SUPEE-10570v2 patch?

**Review by Flyingmana — APPROVED** [review]

**Comment by bassplayer7** [comment]
Can we get this merged now?

**Comment by Flyingmana** [comment]
Iam waiting for at least one other Reviewer, just to make extra sure, as this repo is used by so many others.

**Comment by EricSeastrand** [comment]
@bassplayer7 : If you're in a particular hurry (like I was), keep in mind that you can simply clone Jeroen's fork and work from there. `git clone git@github.com:JeroenBoersma/magento-mirror.git`

**Review by drobinson — APPROVED** [review]

**Comment by drobinson** [comment]
Thank you @JeroenBoersma !

**Comment by JeroenBoersma** [comment]
Yw

**Comment by EricSeastrand** [comment]
@BassemN : You might want to try asking that on the [Magento StackExchange](https://magento.stackexchange.com/) for a faster and more comprehensive answer, but I think the answer is "No, that patch would already be included in the new 1.9.3.9 version".

**Pull request merged**
