### PR TITLE
Delete empty file ".mysql4-upgrade-0.1.9-0.1.10.php.3hidjY" (not present in official release)

### PR DESCRIPTION
**Pull request by EricSeastrand**
This empty file appears to have snuck into the new 1.9.3.7 release. It is not present in the package downloaded from the official Magento site.

### CODE REVIEW

**Comment by drobinson** [comment]
@Schrank Do you know how this could have made it in this commit?  Is it possible there are more like this?

**Comment by Schrank** [comment]
I have no clue. What I did was:
- download the official `magento-1.9.3.7-2017-11-27-05-34-19.tar.bz2` 
- unpack it (can't find any presence of this file!)
- rm -rf * (including dot files except .git)
-  rsync --progress -avr ../magento/ .

I neither can find a source in the tar.bz2 nor in the unpacked files. 😳

Checked the diff file too - just in case I maybe used that, but there is not a bit of this file!?

**Comment by Schrank** [comment]
@willcodeforfood Thanks the check!

**Comment by drobinson** [comment]
Sounds like my process - very possible they ghosted that file out of the release and you grabbed it before then 😄

**Comment by LeeSaferite** [comment]
I've had them do that more than once. It annoys me greatly that they revise the tarball but not the release number.

**Comment by BassemN** [comment]
What about retagging 1.9.3.7 ?

**Comment by drobinson** [comment]
I don't like moving tags...but I guess Magento did.  I'll just move it (sorry everyone that this makes sad)

**Comment by BassemN** [comment]
Thank you :+1:

**Comment by drobinson** [comment]
https://github.com/OpenMage/magento-mirror/releases/tag/1.9.3.7

**Pull request merged**
