### PR TITLE
Import Magento Release 1.9.2.4

### PR DESCRIPTION
**Pull request by digitalpianism**

### CODE REVIEW

**Comment by BassemN** [comment]
:+1:

**Comment by LeeSaferite** [comment]
@digitalpianism I used your PR, but had to fix it.

My process for importing a new release is:

```
cd {magento repo root}
rm -rf * .ht*
tar xvf --strip-components=1 {new release tarball}
git add -A .
git commit -m "Import Magento Release {version number}"
git tag {version number}
git push origin {branch} {version number}
```

This basically removes EVERY file except .gitignore and then uses the new versions. The reason I point this out is your PR was missing some changes to the /var/package directory.

**Comment by LeeSaferite** [comment]
The file used for verifying this PR

```
openssl sha1 magento-1.9.2.4-2016-02-23-06-07-06.tar.bz2 
```

The resulting fingerprint

```
30164c96a620855483066ef4d36f8b7097881499
```

**Comment by digitalpianism** [comment]
@LeeSaferite well thanks for pointing that out and fixing the problem, I will know for the next time.

**Pull request merged**
