### PR TITLE
Magento 1.8

### PR DESCRIPTION
**Pull request by kalenjordan**
Dropped in CE 1.8.0.0 with the copyright's stripped out as a separate commit.

### CODE REVIEW

**Comment by Flyingmana** [comment]
it would be great, if you can also put the changes of the alpha release in

**Comment by kalenjordan** [comment]
Good point.  I might not be able to get to that immediately though.

I'm trying to think about what would be the best way to version 1.8.0.0-alpha vs. 1.8.0.0 including the copyright stripping...?

**Comment by LeeSaferite** [comment]
Not sure why I didn't get a notice for this.

I've just pushed the 1.8 alpha and 1.8 final commits.

If anyone is interested in helping me maintain this repo, please let me know.

**Comment by Flyingmana** [comment]
I am interested :)

**Comment by benmarks** [comment]
I am (and have been) interested.

**Comment by kalenjordan** [comment]
Thanks @LeeSaferite.  The reason for my PR though was to strip out the copyright from the 1.8.0.0 commit to give a "true diff" from 1.7.0.2 to 1.8.0.0.

**Comment by kalenjordan** [comment]
Oh and here's some more context on why I did it:
https://twitter.com/Falkowski/status/382901513640628224

**Comment by LeeSaferite** [comment]
I've created a maintainers team and added @benmarks and @Vinai as I know them personally.

I will also merge this request in after I figure out the best way to handle it as I already pushed the 1.8 branch.

**Comment by LeeSaferite** [comment]
@kalenjordan Did you mind providing the script you used to do the copyright year strip?  We could add it to the standard process for merging new releases.

**Comment by Vinai** [comment]
You sent me the process you use to create new release branches on Skype, but I think it would be a good idea to add that to the repository wiki, or [repository pages](https://help.github.com/categories/20/articles).

**Comment by kalenjordan** [comment]
Here you go:
https://gist.github.com/kalenjordan/6766591

I don't really know the best way to do this across multiple commits though (1.8.0.0 and 1.8.0.0-alpha1).

**Comment by nuno-iglesias** [comment]
I'll happily help you.

2013/9/30 Lee Saferite notifications@github.com

**Comment by SchumacherFM** [comment]
When are you going to create the tag for 1.8.0?

**Pull request merged**
