### PR TITLE
Magento 1.5

### PR DESCRIPTION
**Pull request by mattclegg**
Do you accept pull requests for doc typos?

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Well, I never have before as it's literally just a mirror of the releases.  Not sure what the best approach would be on this one.  Give me a few days to figure it out.

**Comment by mattclegg** [comment]
Ok, no worries. Is there a better way to send patches for magento?

Do you accept pull requests for fixing javascript validation?

**Comment by bnchdrff** [comment]
mattclegg: check out http://www.magentocommerce.com/blog/tomorrow-today/ for info on how to send patches to Magento.  In short, you agree to their contributor's agreement and join their dev list, then send patches to the list.

**Comment by Vinai** [comment]
There is actually a new revised way to contribute, see this post: http://www.magentocommerce.com/blog/comments/be-part-of-the-solution-become-a-magento-contributor/

**Comment by mattclegg** [comment]
The process is still the same tho.

And for the record; the above commits have been applied in r103015 and r103014 respectively.

**Pull request closed without merging**
