### PR TITLE
Import Magento Release 1.9.3.4

### PR DESCRIPTION
**Pull request by borriglione**

### CODE REVIEW

**Comment by davidwindell** [comment]
Argh you beat me to it!! I was just pushing ;)

**Comment by borriglione** [comment]
It was not for the fame ;) ... I need this to check which parts of the code I have to change. I don't want to rollback SUPEE-9767 v1 patch. They are crazy

**Comment by davidwindell** [comment]
Well you are famous in my office now :)

Same here, what a nightmare, more testing desperately needed! This PR looks good to me :+1:

**Comment by Flyingmana** [comment]
diff itself looks ok, did someone check if they get the same diff for 1.9.3.3 vs 1.9.3.4?

@davidwindell  as you already did the push, can you check if the diff is the same?



PS: you can get a PR as diff from this url pattern: https://patch-diff.githubusercontent.com/raw/OpenMage/magento-mirror/pull/50.diff

**Comment by davidwindell** [comment]
Oops, sorry @Flyingmana I've deleted it now.

It looks like this mirror has a diff to compare to 
https://github.com/speedupmate/Magento-CE-Mirror/commit/0655809516a84451e154d999c68f7d1281e22d19

**Comment by Flyingmana** [comment]
thx, looks fine for me. Feels odd to diff 2 diffs.

Do we have another source/reviewer for validating?

**Review by Flyingmana — APPROVED** [review]

**Comment by drobinson** [comment]
I got the same diff - thanks @borriglione

**Comment by BassemN** [comment]
@drobinson Please create a tag for 1.9.3.4 release

**Comment by drobinson** [comment]
@BassemN https://github.com/OpenMage/magento-mirror/releases/tag/1.9.3.4

**Comment by BassemN** [comment]
@drobinson Thx :heart:

**Pull request merged**
