### PR TITLE
Import Magento Release 1.9.3.2 (Code and Copyright Split)

### PR DESCRIPTION
**Pull request by LeeSaferite**
This is the same result as PR #43 with the commit being split in two to surface code changes vs. copyright/eof-newline changes.

### CODE REVIEW

**Comment by JosephMaxwell** [comment]
@LeeSaferite: great idea. Thanks!

**Comment by drobinson** [comment]
Thanks @LeeSaferite - I was hoping to give credit to the other PR but there's been no response to my feedback :)

**Comment by davidwindell** [comment]
@drobinson can you tag this release please? :)

**Comment by drobinson** [comment]
@davidwindell https://github.com/OpenMage/magento-mirror/releases/tag/1.9.3.2

**Comment by luchiano1** [comment]
1

**Pull request merged**
