### PR TITLE
Magento 1.9.4.1

### PR DESCRIPTION
**Pull request by Schrank**

### CODE REVIEW

**Review by kkrieger85 — COMMENTED** [review]
.htaccess and
.htaccess.sample are missing

**Comment by Schrank** [comment]
Thanks!

**Review by kkrieger85 — APPROVED** [review]
Looks good for me

**Comment by NikoGrano** [comment]
Seems good. Please merge. Customers are waiting. LoL @drobinson Can you merge? Thank you!

**Comment by Schrank** [comment]
@Niko9911 Please get the repo, diff it against the zip/gzip from magento.com and assure us, that it is the same :-)

(the last time, the maintainers did that :-) - might speed things up)

**Comment by NikoGrano** [comment]
@Schrank Sorry forgot mention, but I have done it like last time :smiley:

**Comment by JeroenBoersma** [comment]
So, compared with tar...
To reproduce...

- [x] Clone Schrank repo...
- [x] removed all files including hidden
- [x] download tar from Magento.com
- [x] untar archive
- [x] copy files including attributes
- [x] see if there are no changes
- [x] done

Looks good to me

**Comment by Flyingmana** [comment]
merged as I did count 3 approving Reviews.

**Comment by BassemN** [comment]
@Schrank Thanks a lot for splitting the new version into two commits(real changes and copyright changes)

**Comment by BassemN** [comment]
Hello,

Magento 1.9.4.2 has been released on Jun 25, 2019 https://magento.com/tech-resources/download#download2310

**Comment by JeroenBoersma** [comment]
@BassemN https://github.com/OpenMage/magento-mirror/pull/75

**Pull request merged**
